version: "3.4"

services:
  app:
    build:
      context: ./
      dockerfile: ./deployments/app.Dockerfile
      target: app
    expose:
      - 8080:8080
      - 8081:8081
      - 80:80
    networks:
      - application
  app-rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: crypto
    networks:
      - application
networks:
  application:
    driver: bridge
