services:
  app-external-v1:
    build:
      context: ./
      dockerfile: ./deployments/app.Dockerfile
    mem_limit: 512m
    cpus: 0.5
    deploy:
      resources:
        limits:
          cpus: '0.50'     # максимум 50% одного CPU
          memory: 512M     # максимум 512 мегабайт
        reservations:
          cpus: '0.25'     # желательно 25% CPU
          memory: 256M     # желательно 256Мб
    ports:
      - "8080:8080"
      - "8085:8085"
      - "80:80"
    command:
      - "api"
      - "external-v1"
    restart: unless-stopped         # политика рестарта
    networks:
      - application
  app-loader:
    build:
      context: ./
      dockerfile: ./deployments/app.Dockerfile
    mem_limit: 512m
    cpus: 0.5
    deploy:
      resources:
        limits:
          cpus: '0.50'     # максимум 50% одного CPU
          memory: 512M     # максимум 512 мегабайт
        reservations:
          cpus: '0.25'     # желательно 25% CPU
          memory: 256M     # желательно 256Мб
    environment:
      - METRIC_PORT=8081
    ports:
      - "8081:8081"
    command:
      - "daemon"
      - "loader"
    restart: unless-stopped         # политика рестарта
    networks:
      - application
#  app-rabbit:
#    image: rabbitmq:3-management
#    ports:
#      - 5672:5672
#      - 15672:15672
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: crypto
#    networks:
#      - application
networks:
  application:
    driver: bridge
