{
 "title": "Crypto polymath",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Loaded prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(crypto_polymath_loader_count_prices_loaded[1m])) by (exchange)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration loaded prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(crypto_polymath_loader_duration_prices_loaded[1m])) by (exchange)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded candlestick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(crypto_polymath_loader_candlestick_loaded[1m])) by (exchange, interval)",
     "legendFormat": "{{exchange}} : {{interval}}"
    }
   ]
  },
  {
   "title": "Duration loaded candlestick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(crypto_polymath_loader_duration_candlestick_loaded[1m])) by (exchange, interval)",
     "legendFormat": "{{exchange}}: {{interval}}"
    }
   ]
  },
  {
   "title": "Calculated indicator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(crypto_polymath_calculator_calc_indicator[1m])) by (exchange, unit, interval,depth)",
     "legendFormat": "{{exchange}} | unit={{unit}} |  interval= {{interval}} | depth= {{depth}} "
    }
   ]
  },
  {
   "title": "Duration calculated indicator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(crypto_polymath_calculator_duration_calc_indicator[1m])) by (exchange, unit, interval, depth)",
     "legendFormat": "{{exchange}} | unit={{unit}} |  interval= {{interval}} | depth= {{depth}} "
    }
   ]
  },
  {
   "title": "DB queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(db_count_query[1m])) by (query, db)",
     "legendFormat": "{{db}}: {{query}}"
    }
   ]
  },
  {
   "title": "DB duration queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(db_duration_query[1m])) by (query, db)",
     "legendFormat": "{{db}}: {{query}}"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_total[1m])) by (code, url)",
     "legendFormat": "{{code}} :{{url}}"
    }
   ]
  },
  {
   "title": "HTTP request duration ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count[1m])) by (code, url)",
     "legendFormat": "{{code}} :{{url}}"
    }
   ]
  },
  {
   "title": "Deleted indicators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(crypto_polymath_calculator_duration_delete_indicator[1m]))",
     "legendFormat": "indicator"
    },
    {
     "expr": "sum(increase(crypto_polymath_loader_delete_candlestick[1m]))",
     "legendFormat": "candlestick"
    }
   ]
  },
  {
   "title": "GO gorutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "count" }
   ]
  }
 ]
}