// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package spec

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /analysis/{exchange}/{symbol}/{unit}/{interval}/{name}/{indicator_depth}/{depth})
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth(ctx echo.Context, exchange string, symbol string, unit GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit, interval int, name GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName, indicatorDepth GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth, depth GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth) error

	// (GET /candlestick/{exchange}/{symbol}/{unit}/{interval})
	GetCandlestickExchangeSymbolUnitInterval(ctx echo.Context, exchange string, symbol string, unit GetCandlestickExchangeSymbolUnitIntervalParamsUnit, interval string) error

	// (GET /exchange/{exchange}/{symbol})
	GetExchangeExchangeSymbol(ctx echo.Context, exchange string, symbol string) error

	// (GET /indicator/{exchange}/{symbol}/{unit}/{interval}/{name}/{depth})
	GetIndicatorExchangeSymbolUnitIntervalNameDepth(ctx echo.Context, exchange string, symbol string, unit GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit, interval int, name GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName, depth GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth) error

	// (GET /price/{exchange}/{symbol})
	GetPriceExchangeSymbol(ctx echo.Context, exchange string, symbol string) error

	// (GET /prices/exchange/{exchange})
	GetPricesExchangeExchange(ctx echo.Context, exchange string) error

	// (GET /prices/symbol/{symbol})
	GetPricesSymbolSymbol(ctx echo.Context, symbol string) error

	// (GET /server)
	GetServer(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth converts echo context to params.
func (w *ServerInterfaceWrapper) GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithLocation("simple", false, "exchange", runtime.ParamLocationPath, ctx.Param("exchange"), &exchange)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithLocation("simple", false, "symbol", runtime.ParamLocationPath, ctx.Param("symbol"), &symbol)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// ------------- Path parameter "unit" -------------
	var unit GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit

	err = runtime.BindStyledParameterWithLocation("simple", false, "unit", runtime.ParamLocationPath, ctx.Param("unit"), &unit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unit: %s", err))
	}

	// ------------- Path parameter "interval" -------------
	var interval int

	err = runtime.BindStyledParameterWithLocation("simple", false, "interval", runtime.ParamLocationPath, ctx.Param("interval"), &interval)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// ------------- Path parameter "indicator_depth" -------------
	var indicatorDepth GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth

	err = runtime.BindStyledParameterWithLocation("simple", false, "indicator_depth", runtime.ParamLocationPath, ctx.Param("indicator_depth"), &indicatorDepth)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter indicator_depth: %s", err))
	}

	// ------------- Path parameter "depth" -------------
	var depth GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth

	err = runtime.BindStyledParameterWithLocation("simple", false, "depth", runtime.ParamLocationPath, ctx.Param("depth"), &depth)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter depth: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth(ctx, exchange, symbol, unit, interval, name, indicatorDepth, depth)
	return err
}

// GetCandlestickExchangeSymbolUnitInterval converts echo context to params.
func (w *ServerInterfaceWrapper) GetCandlestickExchangeSymbolUnitInterval(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithLocation("simple", false, "exchange", runtime.ParamLocationPath, ctx.Param("exchange"), &exchange)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithLocation("simple", false, "symbol", runtime.ParamLocationPath, ctx.Param("symbol"), &symbol)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// ------------- Path parameter "unit" -------------
	var unit GetCandlestickExchangeSymbolUnitIntervalParamsUnit

	err = runtime.BindStyledParameterWithLocation("simple", false, "unit", runtime.ParamLocationPath, ctx.Param("unit"), &unit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unit: %s", err))
	}

	// ------------- Path parameter "interval" -------------
	var interval string

	err = runtime.BindStyledParameterWithLocation("simple", false, "interval", runtime.ParamLocationPath, ctx.Param("interval"), &interval)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCandlestickExchangeSymbolUnitInterval(ctx, exchange, symbol, unit, interval)
	return err
}

// GetExchangeExchangeSymbol converts echo context to params.
func (w *ServerInterfaceWrapper) GetExchangeExchangeSymbol(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithLocation("simple", false, "exchange", runtime.ParamLocationPath, ctx.Param("exchange"), &exchange)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithLocation("simple", false, "symbol", runtime.ParamLocationPath, ctx.Param("symbol"), &symbol)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExchangeExchangeSymbol(ctx, exchange, symbol)
	return err
}

// GetIndicatorExchangeSymbolUnitIntervalNameDepth converts echo context to params.
func (w *ServerInterfaceWrapper) GetIndicatorExchangeSymbolUnitIntervalNameDepth(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithLocation("simple", false, "exchange", runtime.ParamLocationPath, ctx.Param("exchange"), &exchange)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithLocation("simple", false, "symbol", runtime.ParamLocationPath, ctx.Param("symbol"), &symbol)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// ------------- Path parameter "unit" -------------
	var unit GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit

	err = runtime.BindStyledParameterWithLocation("simple", false, "unit", runtime.ParamLocationPath, ctx.Param("unit"), &unit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unit: %s", err))
	}

	// ------------- Path parameter "interval" -------------
	var interval int

	err = runtime.BindStyledParameterWithLocation("simple", false, "interval", runtime.ParamLocationPath, ctx.Param("interval"), &interval)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// ------------- Path parameter "depth" -------------
	var depth GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth

	err = runtime.BindStyledParameterWithLocation("simple", false, "depth", runtime.ParamLocationPath, ctx.Param("depth"), &depth)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter depth: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIndicatorExchangeSymbolUnitIntervalNameDepth(ctx, exchange, symbol, unit, interval, name, depth)
	return err
}

// GetPriceExchangeSymbol converts echo context to params.
func (w *ServerInterfaceWrapper) GetPriceExchangeSymbol(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithLocation("simple", false, "exchange", runtime.ParamLocationPath, ctx.Param("exchange"), &exchange)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithLocation("simple", false, "symbol", runtime.ParamLocationPath, ctx.Param("symbol"), &symbol)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPriceExchangeSymbol(ctx, exchange, symbol)
	return err
}

// GetPricesExchangeExchange converts echo context to params.
func (w *ServerInterfaceWrapper) GetPricesExchangeExchange(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithLocation("simple", false, "exchange", runtime.ParamLocationPath, ctx.Param("exchange"), &exchange)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPricesExchangeExchange(ctx, exchange)
	return err
}

// GetPricesSymbolSymbol converts echo context to params.
func (w *ServerInterfaceWrapper) GetPricesSymbolSymbol(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithLocation("simple", false, "symbol", runtime.ParamLocationPath, ctx.Param("symbol"), &symbol)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPricesSymbolSymbol(ctx, symbol)
	return err
}

// GetServer converts echo context to params.
func (w *ServerInterfaceWrapper) GetServer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServer(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/analysis/:exchange/:symbol/:unit/:interval/:name/:indicator_depth/:depth", wrapper.GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth)
	router.GET(baseURL+"/candlestick/:exchange/:symbol/:unit/:interval", wrapper.GetCandlestickExchangeSymbolUnitInterval)
	router.GET(baseURL+"/exchange/:exchange/:symbol", wrapper.GetExchangeExchangeSymbol)
	router.GET(baseURL+"/indicator/:exchange/:symbol/:unit/:interval/:name/:depth", wrapper.GetIndicatorExchangeSymbolUnitIntervalNameDepth)
	router.GET(baseURL+"/price/:exchange/:symbol", wrapper.GetPriceExchangeSymbol)
	router.GET(baseURL+"/prices/exchange/:exchange", wrapper.GetPricesExchangeExchange)
	router.GET(baseURL+"/prices/symbol/:symbol", wrapper.GetPricesSymbolSymbol)
	router.GET(baseURL+"/server", wrapper.GetServer)

}
