// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package spec

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Last analysis
	// (GET /analysis/{exchange}/{symbol}/{unit}/{interval}/{name}/{indicator_depth}/{depth})
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth(ctx echo.Context, exchange string, symbol string, unit GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit, interval int, name GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName, indicatorDepth GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth, depth GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth) error
	// Average entry price after adding volume
	// (POST /calculator/trading/avg-entry-price)
	PostCalculatorTradingAvgEntryPrice(ctx echo.Context) error
	// Average entry price after adding by margin amount
	// (POST /calculator/trading/avg-entry-price-by-sum)
	PostCalculatorTradingAvgEntryPriceBySum(ctx echo.Context) error
	// Distance to liquidation in percent
	// (POST /calculator/trading/distance-to-liquidation)
	PostCalculatorTradingDistanceToLiquidation(ctx echo.Context) error
	// Liquidation price of an isolated position
	// (POST /calculator/trading/liquidation-price)
	PostCalculatorTradingLiquidationPrice(ctx echo.Context) error
	// Position risk snapshot at a market price
	// (POST /calculator/trading/risk-at-price)
	PostCalculatorTradingRiskAtPrice(ctx echo.Context) error
	// Add-on simulation (entry, liquidation, risk)
	// (POST /calculator/trading/simulate-add-on)
	PostCalculatorTradingSimulateAddOn(ctx echo.Context) error
	// Spot position PnL in value and percent
	// (POST /calculator/trading/spot-pnl)
	PostCalculatorTradingSpotPnl(ctx echo.Context) error
	// Unrealized PnL
	// (POST /calculator/trading/unrealized-pnl)
	PostCalculatorTradingUnrealizedPnl(ctx echo.Context) error
	// Position size from margin and leverage
	// (POST /calculator/trading/volume-from-margin)
	PostCalculatorTradingVolumeFromMargin(ctx echo.Context) error
	// Last candle-indicators
	// (GET /candle-indicator/{exchange}/{symbol}/{unit}/{interval}/{name})
	GetCandleIndicatorExchangeSymbolUnitIntervalName(ctx echo.Context, exchange string, symbol string, unit GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit, interval int, name GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsName) error
	// Last candlesticks
	// (GET /candlestick/{exchange}/{symbol}/{unit}/{interval})
	GetCandlestickExchangeSymbolUnitInterval(ctx echo.Context, exchange string, symbol string, unit GetCandlestickExchangeSymbolUnitIntervalParamsUnit, interval string) error
	// Send a message to the team
	// (POST /contact)
	PostContact(ctx echo.Context) error
	// Symbol info
	// (GET /exchange/{exchange}/{symbol})
	GetExchangeExchangeSymbol(ctx echo.Context, exchange string, symbol string) error
	// Last indicators
	// (GET /indicator/{exchange}/{symbol}/{unit}/{interval}/{name}/{depth})
	GetIndicatorExchangeSymbolUnitIntervalNameDepth(ctx echo.Context, exchange string, symbol string, unit GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit, interval int, name GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName, depth GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth) error
	// Last symbol price
	// (GET /price/{exchange}/{symbol})
	GetPriceExchangeSymbol(ctx echo.Context, exchange string, symbol string) error
	// Last exchange price
	// (GET /prices/exchange/{exchange})
	GetPricesExchangeExchange(ctx echo.Context, exchange string) error
	// Last prices
	// (GET /prices/symbol/{symbol})
	GetPricesSymbolSymbol(ctx echo.Context, symbol string) error
	// Server information
	// (GET /server)
	GetServer(ctx echo.Context) error
	// Symbol infos
	// (GET /symbols/{exchange}/{category})
	GetSymbolsExchangeCategory(ctx echo.Context, exchange string, category GetSymbolsExchangeCategoryParamsCategory) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth converts echo context to params.
func (w *ServerInterfaceWrapper) GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithOptions("simple", "exchange", ctx.Param("exchange"), &exchange, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", ctx.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// ------------- Path parameter "unit" -------------
	var unit GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit

	err = runtime.BindStyledParameterWithOptions("simple", "unit", ctx.Param("unit"), &unit, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unit: %s", err))
	}

	// ------------- Path parameter "interval" -------------
	var interval int

	err = runtime.BindStyledParameterWithOptions("simple", "interval", ctx.Param("interval"), &interval, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// ------------- Path parameter "indicator_depth" -------------
	var indicatorDepth GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth

	err = runtime.BindStyledParameterWithOptions("simple", "indicator_depth", ctx.Param("indicator_depth"), &indicatorDepth, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter indicator_depth: %s", err))
	}

	// ------------- Path parameter "depth" -------------
	var depth GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth

	err = runtime.BindStyledParameterWithOptions("simple", "depth", ctx.Param("depth"), &depth, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter depth: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth(ctx, exchange, symbol, unit, interval, name, indicatorDepth, depth)
	return err
}

// PostCalculatorTradingAvgEntryPrice converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingAvgEntryPrice(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingAvgEntryPrice(ctx)
	return err
}

// PostCalculatorTradingAvgEntryPriceBySum converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingAvgEntryPriceBySum(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingAvgEntryPriceBySum(ctx)
	return err
}

// PostCalculatorTradingDistanceToLiquidation converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingDistanceToLiquidation(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingDistanceToLiquidation(ctx)
	return err
}

// PostCalculatorTradingLiquidationPrice converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingLiquidationPrice(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingLiquidationPrice(ctx)
	return err
}

// PostCalculatorTradingRiskAtPrice converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingRiskAtPrice(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingRiskAtPrice(ctx)
	return err
}

// PostCalculatorTradingSimulateAddOn converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingSimulateAddOn(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingSimulateAddOn(ctx)
	return err
}

// PostCalculatorTradingSpotPnl converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingSpotPnl(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingSpotPnl(ctx)
	return err
}

// PostCalculatorTradingUnrealizedPnl converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingUnrealizedPnl(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingUnrealizedPnl(ctx)
	return err
}

// PostCalculatorTradingVolumeFromMargin converts echo context to params.
func (w *ServerInterfaceWrapper) PostCalculatorTradingVolumeFromMargin(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCalculatorTradingVolumeFromMargin(ctx)
	return err
}

// GetCandleIndicatorExchangeSymbolUnitIntervalName converts echo context to params.
func (w *ServerInterfaceWrapper) GetCandleIndicatorExchangeSymbolUnitIntervalName(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithOptions("simple", "exchange", ctx.Param("exchange"), &exchange, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", ctx.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// ------------- Path parameter "unit" -------------
	var unit GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit

	err = runtime.BindStyledParameterWithOptions("simple", "unit", ctx.Param("unit"), &unit, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unit: %s", err))
	}

	// ------------- Path parameter "interval" -------------
	var interval int

	err = runtime.BindStyledParameterWithOptions("simple", "interval", ctx.Param("interval"), &interval, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsName

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCandleIndicatorExchangeSymbolUnitIntervalName(ctx, exchange, symbol, unit, interval, name)
	return err
}

// GetCandlestickExchangeSymbolUnitInterval converts echo context to params.
func (w *ServerInterfaceWrapper) GetCandlestickExchangeSymbolUnitInterval(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithOptions("simple", "exchange", ctx.Param("exchange"), &exchange, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", ctx.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// ------------- Path parameter "unit" -------------
	var unit GetCandlestickExchangeSymbolUnitIntervalParamsUnit

	err = runtime.BindStyledParameterWithOptions("simple", "unit", ctx.Param("unit"), &unit, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unit: %s", err))
	}

	// ------------- Path parameter "interval" -------------
	var interval string

	err = runtime.BindStyledParameterWithOptions("simple", "interval", ctx.Param("interval"), &interval, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCandlestickExchangeSymbolUnitInterval(ctx, exchange, symbol, unit, interval)
	return err
}

// PostContact converts echo context to params.
func (w *ServerInterfaceWrapper) PostContact(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostContact(ctx)
	return err
}

// GetExchangeExchangeSymbol converts echo context to params.
func (w *ServerInterfaceWrapper) GetExchangeExchangeSymbol(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithOptions("simple", "exchange", ctx.Param("exchange"), &exchange, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", ctx.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExchangeExchangeSymbol(ctx, exchange, symbol)
	return err
}

// GetIndicatorExchangeSymbolUnitIntervalNameDepth converts echo context to params.
func (w *ServerInterfaceWrapper) GetIndicatorExchangeSymbolUnitIntervalNameDepth(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithOptions("simple", "exchange", ctx.Param("exchange"), &exchange, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", ctx.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// ------------- Path parameter "unit" -------------
	var unit GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit

	err = runtime.BindStyledParameterWithOptions("simple", "unit", ctx.Param("unit"), &unit, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unit: %s", err))
	}

	// ------------- Path parameter "interval" -------------
	var interval int

	err = runtime.BindStyledParameterWithOptions("simple", "interval", ctx.Param("interval"), &interval, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// ------------- Path parameter "depth" -------------
	var depth GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth

	err = runtime.BindStyledParameterWithOptions("simple", "depth", ctx.Param("depth"), &depth, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter depth: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIndicatorExchangeSymbolUnitIntervalNameDepth(ctx, exchange, symbol, unit, interval, name, depth)
	return err
}

// GetPriceExchangeSymbol converts echo context to params.
func (w *ServerInterfaceWrapper) GetPriceExchangeSymbol(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithOptions("simple", "exchange", ctx.Param("exchange"), &exchange, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", ctx.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPriceExchangeSymbol(ctx, exchange, symbol)
	return err
}

// GetPricesExchangeExchange converts echo context to params.
func (w *ServerInterfaceWrapper) GetPricesExchangeExchange(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithOptions("simple", "exchange", ctx.Param("exchange"), &exchange, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPricesExchangeExchange(ctx, exchange)
	return err
}

// GetPricesSymbolSymbol converts echo context to params.
func (w *ServerInterfaceWrapper) GetPricesSymbolSymbol(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", ctx.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPricesSymbolSymbol(ctx, symbol)
	return err
}

// GetServer converts echo context to params.
func (w *ServerInterfaceWrapper) GetServer(ctx echo.Context) error {
	var err error

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServer(ctx)
	return err
}

// GetSymbolsExchangeCategory converts echo context to params.
func (w *ServerInterfaceWrapper) GetSymbolsExchangeCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "exchange" -------------
	var exchange string

	err = runtime.BindStyledParameterWithOptions("simple", "exchange", ctx.Param("exchange"), &exchange, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter exchange: %s", err))
	}

	// ------------- Path parameter "category" -------------
	var category GetSymbolsExchangeCategoryParamsCategory

	err = runtime.BindStyledParameterWithOptions("simple", "category", ctx.Param("category"), &category, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category: %s", err))
	}

	ctx.Set(TokenHeaderScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSymbolsExchangeCategory(ctx, exchange, category)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/analysis/:exchange/:symbol/:unit/:interval/:name/:indicator_depth/:depth", wrapper.GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth)
	router.POST(baseURL+"/calculator/trading/avg-entry-price", wrapper.PostCalculatorTradingAvgEntryPrice)
	router.POST(baseURL+"/calculator/trading/avg-entry-price-by-sum", wrapper.PostCalculatorTradingAvgEntryPriceBySum)
	router.POST(baseURL+"/calculator/trading/distance-to-liquidation", wrapper.PostCalculatorTradingDistanceToLiquidation)
	router.POST(baseURL+"/calculator/trading/liquidation-price", wrapper.PostCalculatorTradingLiquidationPrice)
	router.POST(baseURL+"/calculator/trading/risk-at-price", wrapper.PostCalculatorTradingRiskAtPrice)
	router.POST(baseURL+"/calculator/trading/simulate-add-on", wrapper.PostCalculatorTradingSimulateAddOn)
	router.POST(baseURL+"/calculator/trading/spot-pnl", wrapper.PostCalculatorTradingSpotPnl)
	router.POST(baseURL+"/calculator/trading/unrealized-pnl", wrapper.PostCalculatorTradingUnrealizedPnl)
	router.POST(baseURL+"/calculator/trading/volume-from-margin", wrapper.PostCalculatorTradingVolumeFromMargin)
	router.GET(baseURL+"/candle-indicator/:exchange/:symbol/:unit/:interval/:name", wrapper.GetCandleIndicatorExchangeSymbolUnitIntervalName)
	router.GET(baseURL+"/candlestick/:exchange/:symbol/:unit/:interval", wrapper.GetCandlestickExchangeSymbolUnitInterval)
	router.POST(baseURL+"/contact", wrapper.PostContact)
	router.GET(baseURL+"/exchange/:exchange/:symbol", wrapper.GetExchangeExchangeSymbol)
	router.GET(baseURL+"/indicator/:exchange/:symbol/:unit/:interval/:name/:depth", wrapper.GetIndicatorExchangeSymbolUnitIntervalNameDepth)
	router.GET(baseURL+"/price/:exchange/:symbol", wrapper.GetPriceExchangeSymbol)
	router.GET(baseURL+"/prices/exchange/:exchange", wrapper.GetPricesExchangeExchange)
	router.GET(baseURL+"/prices/symbol/:symbol", wrapper.GetPricesSymbolSymbol)
	router.GET(baseURL+"/server", wrapper.GetServer)
	router.GET(baseURL+"/symbols/:exchange/:category", wrapper.GetSymbolsExchangeCategory)

}
