// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package spec

import (
	"time"
)

// Defines values for CandleIndicatorItemDirection.
const (
	CandleIndicatorItemDirectionMinus1 CandleIndicatorItemDirection = -1
	CandleIndicatorItemDirectionN0     CandleIndicatorItemDirection = 0
	CandleIndicatorItemDirectionN1     CandleIndicatorItemDirection = 1
)

// Defines values for CandlestickItemDirection.
const (
	CandlestickItemDirectionMinus1 CandlestickItemDirection = -1
	CandlestickItemDirectionN0     CandlestickItemDirection = 0
	CandlestickItemDirectionN1     CandlestickItemDirection = 1
)

// Defines values for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit.
const (
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitD  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "D"
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitH  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "H"
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitM  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "m"
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitM1 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "M"
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitW  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "W"
)

// Defines values for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName.
const (
	MACDMainLine         GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "MACDMainLine"
	MACDSHistogram       GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "MACDSHistogram"
	MACDSignalLine       GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "MACDSignalLine"
	RSI                  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "RSI"
	RatioCandleToEMA     GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "RatioCandleToEMA"
	RatioCandleToMA      GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "RatioCandleToMA"
	StochasticSignalLine GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "StochasticSignalLine"
	TrendByEMA           GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "TrendByEMA"
	TrendByMA            GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName = "TrendByMA"
)

// Defines values for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth.
const (
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN1  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 1
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN10 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 10
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN12 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 12
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN14 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 14
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN20 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 20
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN26 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 26
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN50 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 50
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN9  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 9
)

// Defines values for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth.
const (
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN1  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 1
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN10 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 10
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN12 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 12
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN14 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 14
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN20 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 20
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN26 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 26
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN3  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 3
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN50 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 50
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN9  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 9
)

// Defines values for GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit.
const (
	GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnitD  GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit = "D"
	GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnitH  GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit = "H"
	GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnitM  GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit = "m"
	GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnitM1 GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit = "M"
	GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnitW  GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit = "W"
)

// Defines values for GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsName.
const (
	HeikenAshi GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsName = "HeikenAshi"
)

// Defines values for GetCandlestickExchangeSymbolUnitIntervalParamsUnit.
const (
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitD  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "D"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitH  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "H"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitM  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "m"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitM1 GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "M"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitW  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "W"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit.
const (
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitD  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "D"
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitH  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "H"
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitM  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "m"
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitM1 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "M"
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitW  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "W"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName.
const (
	EMA                     GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "EMA"
	MA                      GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "MA"
	PriceChanges            GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "PriceChanges"
	StochasticMainLine      GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "StochasticMainLine"
	Trend                   GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "Trend"
	TypeCandle              GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "TypeCandle"
	VolatilityCandlePercent GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "VolatilityCandlePercent"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth.
const (
	N1  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 1
	N10 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 10
	N12 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 12
	N14 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 14
	N20 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 20
	N26 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 26
	N3  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 3
	N50 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 50
	N9  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 9
)

// Defines values for GetSymbolsExchangeCategoryParamsCategory.
const (
	Future GetSymbolsExchangeCategoryParamsCategory = "future"
	Spot   GetSymbolsExchangeCategoryParamsCategory = "spot"
)

// AnalysisInfo defines model for AnalysisInfo.
type AnalysisInfo struct {
	Depth          []int  `json:"depth"`
	Description    string `json:"description"`
	IndicatorDepth []int  `json:"indicator_depth"`

	// Name Name analysis
	Name string `json:"name"`
}

// AnalysisItem defines model for AnalysisItem.
type AnalysisItem struct {
	Datetime time.Time `json:"datetime"`
	Value    float32   `json:"value"`
}

// AnalysisResponse defines model for AnalysisResponse.
type AnalysisResponse = []AnalysisItem

// CandleIndicatorItem defines model for CandleIndicatorItem.
type CandleIndicatorItem struct {
	CloseLocation     float32                      `json:"close_location"`
	ClosePrice        float32                      `json:"close_price"`
	Direction         CandleIndicatorItemDirection `json:"direction"`
	HighPrice         float32                      `json:"high_price"`
	LowPrice          float32                      `json:"low_price"`
	OpenLocation      float32                      `json:"open_location"`
	OpenPrice         float32                      `json:"open_price"`
	SizeBodyInPercent float32                      `json:"size_body_in_percent"`
	StartTime         time.Time                    `json:"start_time"`
}

// CandleIndicatorItemDirection defines model for CandleIndicatorItem.Direction.
type CandleIndicatorItemDirection int

// CandleIndicatorResponse defines model for CandleIndicatorResponse.
type CandleIndicatorResponse = []CandleIndicatorItem

// CandlestickItem defines model for CandlestickItem.
type CandlestickItem struct {
	CloseLocation     float32                  `json:"close_location"`
	ClosePrice        float32                  `json:"close_price"`
	Direction         CandlestickItemDirection `json:"direction"`
	HighPrice         float32                  `json:"high_price"`
	LowPrice          float32                  `json:"low_price"`
	OpenLocation      float32                  `json:"open_location"`
	OpenPrice         float32                  `json:"open_price"`
	SizeBodyInPercent float32                  `json:"size_body_in_percent"`
	StartTime         time.Time                `json:"start_time"`
	Volume            float32                  `json:"volume"`
}

// CandlestickItemDirection defines model for CandlestickItem.Direction.
type CandlestickItemDirection int

// CandlesticksResponse defines model for CandlesticksResponse.
type CandlesticksResponse = []CandlestickItem

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// IndicatorInfo defines model for IndicatorInfo.
type IndicatorInfo struct {
	Depth       []int  `json:"depth"`
	Description string `json:"description"`

	// Name Name indicator
	Name string `json:"name"`
}

// IndicatorItem defines model for IndicatorItem.
type IndicatorItem struct {
	Datetime time.Time `json:"datetime"`
	Value    float32   `json:"value"`
}

// IndicatorResponse defines model for IndicatorResponse.
type IndicatorResponse = []IndicatorItem

// PriceResponse defines model for PriceResponse.
type PriceResponse struct {
	// Exchange Name exchange
	Exchange string `json:"exchange"`

	// Symbol Name symbol
	Symbol string `json:"symbol"`

	// Value Last price value
	Value float32 `json:"value"`
}

// PricesResponse defines model for PricesResponse.
type PricesResponse = []PriceResponse

// ServerInfoResponse defines model for ServerInfoResponse.
type ServerInfoResponse struct {
	Analysis       []AnalysisInfo  `json:"analysis"`
	Depths         []int           `json:"depths"`
	Exchanges      []string        `json:"exchanges"`
	IndicatorDepth []int           `json:"indicator_depth"`
	Indicators     []IndicatorInfo `json:"indicators"`
	Intervals      []UnitIntervals `json:"intervals"`
	Symbols        []string        `json:"symbols"`
	Time           time.Time       `json:"time"`
	Units          []string        `json:"units"`
}

// SymbolInfoResponse defines model for SymbolInfoResponse.
type SymbolInfoResponse struct {
	// BaseAsset Base coin
	BaseAsset string `json:"base_asset"`

	// Exchange Name exchange
	Exchange string `json:"exchange"`

	// IsExist Symbol exist in exchange
	IsExist bool `json:"is_exist"`

	// QuoteAsset Quote coin
	QuoteAsset string `json:"quote_asset"`

	// Symbol Name symbol
	Symbol string `json:"symbol"`
}

// UnitIntervals Support interval
type UnitIntervals struct {
	// Unit Unit value
	Unit   string `json:"unit"`
	Values []int  `json:"values"`
}

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit defines parameters for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth.
type GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit string

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName defines parameters for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth.
type GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsName string

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth defines parameters for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth.
type GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth int

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth defines parameters for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth.
type GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth int

// GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit defines parameters for GetCandleIndicatorExchangeSymbolUnitIntervalName.
type GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsUnit string

// GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsName defines parameters for GetCandleIndicatorExchangeSymbolUnitIntervalName.
type GetCandleIndicatorExchangeSymbolUnitIntervalNameParamsName string

// GetCandlestickExchangeSymbolUnitIntervalParamsUnit defines parameters for GetCandlestickExchangeSymbolUnitInterval.
type GetCandlestickExchangeSymbolUnitIntervalParamsUnit string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth int

// GetSymbolsExchangeCategoryParamsCategory defines parameters for GetSymbolsExchangeCategory.
type GetSymbolsExchangeCategoryParamsCategory string
