// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package v1

import (
	"time"
)

// Defines values for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit.
const (
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitD  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "D"
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitH  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "H"
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitM  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "m"
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitM1 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "M"
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnitW  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit = "W"
)

// Defines values for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth.
const (
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN1  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 1
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN10 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 10
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN20 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 20
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepthN50 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth = 50
)

// Defines values for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth.
const (
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN1  GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 1
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN10 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 10
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN20 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 20
	GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepthN50 GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth = 50
)

// Defines values for GetCandlestickExchangeSymbolUnitIntervalParamsUnit.
const (
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitD  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "D"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitH  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "H"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitM  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "m"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitM1 GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "M"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitW  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "W"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit.
const (
	D  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "D"
	H  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "H"
	M  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "m"
	M1 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "M"
	W  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "W"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName.
const (
	EMA                     GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "EMA"
	MA                      GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "MA"
	PriceChanges            GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "PriceChanges"
	Trend                   GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "Trend"
	TypeCandle              GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "TypeCandle"
	VolatilityCandlePercent GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "VolatilityCandlePercent"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth.
const (
	N1  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 1
	N10 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 10
	N20 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 20
	N50 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 50
)

// AnalysisItem defines model for AnalysisItem.
type AnalysisItem struct {
	Datetime time.Time `json:"datetime"`
	Value    float32   `json:"value"`
}

// AnalysisResponse defines model for AnalysisResponse.
type AnalysisResponse = []AnalysisItem

// CandlestickItem defines model for CandlestickItem.
type CandlestickItem struct {
	ClosePrice float32   `json:"close_price"`
	HighPrice  float32   `json:"high_price"`
	LowPrice   float32   `json:"low_price"`
	OpenPrice  float32   `json:"open_price"`
	StartTime  time.Time `json:"start_time"`
	Volume     float32   `json:"volume"`
}

// CandlesticksResponse defines model for CandlesticksResponse.
type CandlesticksResponse = []CandlestickItem

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// IndicatorItem defines model for IndicatorItem.
type IndicatorItem struct {
	Datetime time.Time `json:"datetime"`
	Value    float32   `json:"value"`
}

// IndicatorResponse defines model for IndicatorResponse.
type IndicatorResponse = []IndicatorItem

// PriceResponse defines model for PriceResponse.
type PriceResponse struct {
	// Exchange Name exchange
	Exchange string `json:"exchange"`

	// Symbol Name symbol
	Symbol string `json:"symbol"`

	// Value Last price value
	Value float32 `json:"value"`
}

// PricesResponse defines model for PricesResponse.
type PricesResponse = []PriceResponse

// ServerInfoResponse defines model for ServerInfoResponse.
type ServerInfoResponse struct {
	Time time.Time `json:"time"`
}

// SymbolInfoResponse defines model for SymbolInfoResponse.
type SymbolInfoResponse struct {
	// BaseAsset Base coin
	BaseAsset string `json:"base_asset"`

	// Exchange Name exchange
	Exchange string `json:"exchange"`

	// QuoteAsset Quote coin
	QuoteAsset string `json:"quote_asset"`

	// Symbol Name symbol
	Symbol string `json:"symbol"`
}

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit defines parameters for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth.
type GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsUnit string

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth defines parameters for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth.
type GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsIndicatorDepth int

// GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth defines parameters for GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepth.
type GetAnalysisExchangeSymbolUnitIntervalNameIndicatorDepthDepthParamsDepth int

// GetCandlestickExchangeSymbolUnitIntervalParamsUnit defines parameters for GetCandlestickExchangeSymbolUnitInterval.
type GetCandlestickExchangeSymbolUnitIntervalParamsUnit string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth int
