// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package v1

import (
	"time"
)

// Defines values for GetCandlestickExchangeSymbolUnitIntervalParamsUnit.
const (
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitD  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "D"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitH  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "H"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitM  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "m"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitM1 GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "M"
	GetCandlestickExchangeSymbolUnitIntervalParamsUnitW  GetCandlestickExchangeSymbolUnitIntervalParamsUnit = "W"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit.
const (
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitD  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "D"
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitH  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "H"
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitM  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "m"
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitM1 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "M"
	GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnitW  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit = "W"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName.
const (
	EMA                     GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "EMA"
	MA                      GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "MA"
	Trend                   GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "Trend"
	TypeCandle              GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "TypeCandle"
	VolatilityCandlePercent GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName = "VolatilityCandlePercent"
)

// Defines values for GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth.
const (
	N1  GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 1
	N10 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 10
	N20 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 20
	N50 GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth = 50
)

// CandlestickItem defines model for CandlestickItem.
type CandlestickItem struct {
	ClosePrice float32   `json:"close_price"`
	HighPrice  float32   `json:"high_price"`
	LowPrice   float32   `json:"low_price"`
	OpenPrice  float32   `json:"open_price"`
	StartTime  time.Time `json:"start_time"`
	Volume     float32   `json:"volume"`
}

// CandlesticksResponse defines model for CandlesticksResponse.
type CandlesticksResponse = []CandlestickItem

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// IndicatorItem defines model for IndicatorItem.
type IndicatorItem struct {
	Datetime time.Time `json:"datetime"`
	Value    float32   `json:"value"`
}

// IndicatorResponse defines model for IndicatorResponse.
type IndicatorResponse = []IndicatorItem

// PriceResponse defines model for PriceResponse.
type PriceResponse struct {
	// Exchange Name exchange
	Exchange string `json:"exchange"`

	// Symbol Name symbol
	Symbol string `json:"symbol"`

	// Value Last price value
	Value float32 `json:"value"`
}

// PricesResponse defines model for PricesResponse.
type PricesResponse = []PriceResponse

// ServerInfoResponse defines model for ServerInfoResponse.
type ServerInfoResponse struct {
	Time time.Time `json:"time"`
}

// GetCandlestickExchangeSymbolUnitIntervalParamsUnit defines parameters for GetCandlestickExchangeSymbolUnitInterval.
type GetCandlestickExchangeSymbolUnitIntervalParamsUnit string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsUnit string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsName string

// GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth defines parameters for GetIndicatorExchangeSymbolUnitIntervalNameDepth.
type GetIndicatorExchangeSymbolUnitIntervalNameDepthParamsDepth int
